name: mathriddles
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: TI84Font
      fonts:
        - asset: fonts/texas_instruments_ti84_series.ttf
    - family: Handjet
      fonts:
        - asset: fonts/Handjet-Regular.ttf
    - family: TI84Fontp
      fonts:
        - asset: fonts/texas_instruments_ti84_seriesp.ttf
    - family: Fun
      fonts:
        - asset: fonts/fun.ttf

  # If you have other flutter configurations like assets, they go here.
  # For example:
  # assets:
  #   - images/


