// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1eSEZqD4Ur6r5VAtmsMKOFUS4lKHByH4',
    appId: '1:706843254905:web:eb74db7fbd520dd51db4a8',
    messagingSenderId: '706843254905',
    projectId: 'math-riddler',
    authDomain: 'math-riddler.firebaseapp.com',
    storageBucket: 'math-riddler.appspot.com',
    measurementId: 'G-B6FL2G98XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRqyiIjdbsFcWJCRhbCYo3KnLQ-H6FEsA',
    appId: '1:706843254905:android:d259df70a145e1ad1db4a8',
    messagingSenderId: '706843254905',
    projectId: 'math-riddler',
    storageBucket: 'math-riddler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkRpkjXe4qb3BoEqKlSBlbtaqdjrvYELc',
    appId: '1:706843254905:ios:53d25a2b6f14392d1db4a8',
    messagingSenderId: '706843254905',
    projectId: 'math-riddler',
    storageBucket: 'math-riddler.appspot.com',
    iosClientId: '706843254905-t7g0sdgecqqngefu6gsboqv35enpmore.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathriddles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkRpkjXe4qb3BoEqKlSBlbtaqdjrvYELc',
    appId: '1:706843254905:ios:e6fb46c1cab739081db4a8',
    messagingSenderId: '706843254905',
    projectId: 'math-riddler',
    storageBucket: 'math-riddler.appspot.com',
    iosClientId: '706843254905-56f4tvmedjbkavqoum4u4r574sd6be7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathriddles.RunnerTests',
  );
}
